#Config file for the ASM part of GTNHCoreMod
#Thu Sep 17 15:19:30 UTC 2026
displayedModpackVersion=2.9.0-beta-3
downloadOnlyOnce=true
patchItemFocusWarding=true
savedVersion=2.9.61
showConfirmExitWindow=false
