#Config file for the ASM part of GTNHCoreMod
#Sun Sep 13 22:39:59 BRT 2026
displayedModpackVersion=2.9.0-beta-3
downloadOnlyOnce=true
patchItemFocusWarding=true
savedVersion=2.9.61
showConfirmExitWindow=false
