#Config file for the ASM part of GTNHCoreMod
#Sun Sep 06 12:24:49 BRT 2026
displayedModpackVersion=2.9.0-beta-3
downloadOnlyOnce=true
patchItemFocusWarding=true
savedVersion=2.9.61
showConfirmExitWindow=false
