#Coremod SortingIndex override: SortingIndex.<coremod class>=<number> sets a coremod's load order.
#Example: SortingIndex.com.mitchej123.hodgepodge.core.HodgepodgeCore=1
#Thu Oct 08 12:19:03 UTC 2026
enableSortingIndexOverrides=true
