#Coremod SortingIndex override: SortingIndex.<coremod class>=<number> sets a coremod's load order.
#Example: SortingIndex.com.mitchej123.hodgepodge.core.HodgepodgeCore=1
#Fri Sep 18 02:59:55 UTC 2026
enableSortingIndexOverrides=true
