#Coremod SortingIndex override: SortingIndex.<coremod class>=<number> sets a coremod's load order.
#Example: SortingIndex.com.mitchej123.hodgepodge.core.HodgepodgeCore=1
#Tue Sep 01 11:17:59 UTC 2026
enableSortingIndexOverrides=true
